# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [18]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)

print('list(a)', list(a))      # 只會把第一層元素轉換成list
print('tolist(a):',a.tolist()) # 多層轉換

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
list(a) [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist(a): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [24]:
import numpy as np
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)     # 一維
print(a.shape)    # 大小(6, )
print(a.size)     # 陣列中有 6 個元素
print(a.dtype)    # 資料型態為 int32
print(a.itemsize) # 每個元素所佔的空間
print(len(a))     # 陣列長度為 6
print(type(a))    # 陣列型態為 numpy.ndarray

[6 7 9 7 2 9]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [23]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.ndim)     # 二維
print(b.shape)    # 大小(3,4)
print(b.size)     # 陣列中有 12 個元素
print(b.dtype)    # 資料型態為 int32
print(b.itemsize) # 每個元素所佔的空間
print(len(b))     # 陣列長度為 3
print(type(b))    # 陣列型態為 numpy.ndarray

[[9 2 3 2]
 [3 2 2 9]
 [0 4 9 4]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [25]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim)     # 三維
print(c.shape)    # 大小(2, 3, 2)
print(c.size)     # 陣列中有 12 個元素
print(c.dtype)    # 資料型態為 int32
print(c.itemsize) # 每個元素所佔的空間
print(len(c))     # 陣列長度為 3
print(type(c))    # 陣列型態為 numpy.ndarray

[[[0 5]
  [8 8]
  [8 7]]

 [[3 2]
  [8 7]
  [8 5]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [26]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    
    newlist=[]
    for obj in iterable:
        newlist.append(tolist(obj))
    return newlist

  

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 7, 9, 7, 2, 9]
[[9, 2, 3, 2], [3, 2, 2, 9], [0, 4, 9, 4]]
[[[0, 5], [8, 8], [8, 7]], [[3, 2], [8, 7], [8, 5]]]
