# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [1]:
import numpy as np

a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

print(a + a)
print(a + b)
print(a + c)
print(a + d)
print(a + e)  # shape不同，一個是1*4 另一1*2，無法用廣播來延長，

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [7]:
import numpy as np

A = np.ones(3)*1
B = np.ones(3)*2
print(A)
print(B)

C = A+B
D = A*(-1)/2
print(C*D)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]


In [8]:
# 用迴圈
c = []
for i,j in zip(A,B):
        c.append((i+j)*(-i/2))
print(c)

[-1.5, -1.5, -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [12]:
A = np.ones((1,6))
B = np.ones((6,1))

print(A)
print(B)

print(A*B)                # 單純乘法，Broadcasting

print(np.dot(A,B))        # 內積
print(A@B)

print(np.cross(A,B))      # 外積做不出來。dimension must be 2 or 3



[[1. 1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
[[6.]]


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)