# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [23]:
import numpy as np

a = np.arange(1,12,1)
print(a)
print(a[ [ True,True,True,True,True,True,True,True,True,True,True]])
          
          
a[(a>=3) & (a<=6)] *=-1
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [18]:
A = np.random.rand(3, 6)

print(A > 0.5)
print(A[ A> 0.5])
print(A[ A> 0.5].size)

[[False False  True False False  True]
 [ True  True  True False False False]
 [ True  True  True  True False False]]
[0.5688776  0.85992547 0.50993651 0.98747638 0.54353565 0.70679114
 0.52860174 0.85289626 0.95068796]
9
