# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [49]:
import numpy as np

a = np.arange(6)
print('Original:')
print(a)

print('Test:')
print(a.sum()) 
print(np.sum(a))
print(sum(a))

b = np.arange(9).reshape((3, 3))
print('Original:')
print(b)

print('Test:')
print(b.sum())      # 所有元素相加
print(np.sum(b))    # 所有元素相加
print(sum(b))       # 同一column相加，回傳 axis=0 的總合

Original:
[0 1 2 3 4 5]
Test:
15
15
15
Original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Test:
36
36
[ 9 12 15]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [50]:
import numpy as np
a = np.random.random((5, 5))
print('Original:')
print(a)

# 資料的正規化是將原始資料的數據按比例縮放於 [0, 1] 區間中，且不改變其原本分佈。
normala = (a-a.min())/(a.max()-a.min())

print('After Normalization:')
print(normala)

Original:
[[0.83677021 0.53790522 0.15486165 0.5680829  0.40647717]
 [0.72301123 0.86883757 0.96532772 0.75454362 0.74988046]
 [0.60203085 0.55927267 0.27940622 0.04190708 0.13456173]
 [0.63708951 0.2209762  0.32302955 0.10085404 0.27095281]
 [0.23192073 0.34956723 0.88806513 0.74255611 0.59748359]]
After Normalization:
[[0.8607812  0.53713131 0.12232191 0.56981164 0.39480392]
 [0.73758818 0.89550791 1.         0.77173556 0.76668568]
 [0.60657489 0.56027077 0.25719496 0.         0.10033851]
 [0.64454096 0.19391934 0.30443598 0.06383544 0.24804052]
 [0.2057715  0.33317444 0.91633001 0.75875392 0.60165052]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [51]:
import numpy as np

a = np.random.randint(1,100,10)
print('Original Data:')
print(a)

print('Maximum:')
print(np.max(a))

print('Location of Max:')
print(np.argmax(a))

a[np.argmax(a)] = -1
print('Update Data:')
print(a)

Original Data:
[95 14  4 42 88 41 87 30 85 35]
Maximum:
95
Location of Max:
0
Update Data:
[-1 14  4 42 88 41 87 30 85 35]
