# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [3]:
import numpy as np
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[9 1 5 ... 3 3 4]
  [7 5 0 ... 6 2 8]
  [4 3 4 ... 3 1 4]
  ...
  [4 4 7 ... 7 7 8]
  [8 7 7 ... 1 3 7]
  [6 7 6 ... 0 7 2]]

 [[7 6 8 ... 2 1 5]
  [8 0 7 ... 3 8 3]
  [9 1 3 ... 6 1 0]
  ...
  [5 4 3 ... 6 6 8]
  [0 4 2 ... 2 3 7]
  [0 6 8 ... 9 3 6]]

 [[3 9 0 ... 5 5 0]
  [1 4 0 ... 9 8 5]
  [6 1 3 ... 6 8 7]
  ...
  [5 3 4 ... 2 2 2]
  [7 5 0 ... 8 2 1]
  [7 2 0 ... 4 9 3]]

 ...

 [[0 3 7 ... 6 7 1]
  [0 7 9 ... 2 8 2]
  [4 8 1 ... 4 5 3]
  ...
  [6 6 5 ... 0 3 3]
  [0 0 7 ... 9 1 7]
  [9 6 2 ... 2 2 0]]

 [[3 0 4 ... 5 9 0]
  [2 7 9 ... 6 9 3]
  [0 6 9 ... 5 3 8]
  ...
  [6 8 0 ... 1 9 8]
  [6 6 1 ... 1 5 4]
  [2 2 5 ... 6 3 5]]

 [[9 5 7 ... 9 6 6]
  [6 0 2 ... 7 6 1]
  [3 6 7 ... 2 6 6]
  ...
  [6 6 4 ... 5 2 8]
  [6 3 4 ... 8 2 4]
  [2 0 2 ... 3 8 2]]]


In [11]:
%timeit -n 10 a = 2

for row in Z:
        for a in row:
            a+=1


62.9 ns ± 15.8 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
%timeit -n 10 a = 2

for d in Z.flat:
    d+=1

201 ns ± 71 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
%timeit -n 10 a = 2

for d in np.nditer(Z):
    d = d+1

71.4 ns ± 13.6 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [60]:
import numpy as np
Z = np.random.randint(1,13,50) # 1-12間隨機產生50個正整數
print(Z)

count = np.bincount(Z)         # np.bincount: 依序列出0-12的個數
print('個數:',count)
number = np.argmax(count)      # np.argmax: 指出個數中最大值的位置，剛好對應數字本身
print('數值:',number)
print('位置:',np.where(Z == number))         # np.where: 標示位置

[ 4 11  5 11  1 11  1 12  8  4  7  2  1  2 10  2 10  9  1  3  7  4 11 11
  4  6  1  3 10 11  8  4  2  4 11 10  5  6  5  9  7  9  3  5  3  3 12  8
 10  2]
個數: [0 5 5 5 6 4 2 3 3 3 5 7 2]
數值: 11
位置: (array([ 1,  3,  5, 22, 23, 29, 34], dtype=int64),)


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [77]:
a = np.random.randint(10, size=6) 
print('a.tolist():',a.tolist())
print('list(a):',list(a))


b = np.random.randint(10, size=(3,4)) 
print(' ')
print('b.tolist():',b.tolist())
print('list(b):',list(b))


c = np.random.randint(10, size=(2,3,2))
print(' ')
print('c.tolist()',c.tolist())
print('list(c):',list(c))
print(' ')

def list(iterable):
    return iterable.tolist()

print('list(a) -> a.tolist:')
print(list(a))
print('list(b) -> b.tolist:')
print(list(b))
print('list(c) -> c.tolist:')
print(list(c))

a.tolist(): [4, 3, 2, 7, 4, 1]
list(a): [4, 3, 2, 7, 4, 1]
 
b.tolist(): [[2, 4, 9, 6], [4, 5, 8, 8], [2, 8, 8, 1]]
list(b): [[2, 4, 9, 6], [4, 5, 8, 8], [2, 8, 8, 1]]
 
c.tolist() [[[4, 5], [2, 2], [3, 6]], [[3, 2], [8, 5], [4, 8]]]
list(c): [[[4, 5], [2, 2], [3, 6]], [[3, 2], [8, 5], [4, 8]]]
 
list(a) -> a.tolist:
[4, 3, 2, 7, 4, 1]
list(b) -> b.tolist:
[[2, 4, 9, 6], [4, 5, 8, 8], [2, 8, 8, 1]]
list(c) -> c.tolist:
[[[4, 5], [2, 2], [3, 6]], [[3, 2], [8, 5], [4, 8]]]
